---
layout: cv
title: Nathaniel Sparks's Resume
---

# Nathaniel Sparks  
Aspiring Data Scientist | Manager | Problem Solver

<div id="webaddress">
<a href="mailto:w4rren86@gmail.com">w4rren86@gmail.com</a>
| <a href="https://www.linkedin.com/in/nathaniel-sparks-a219b0220">LinkedIn</a>
| <a href="https://github.com/Nathaniel-Sparks">GitHub</a>
</div>

## Summary of Qualifications

- SQL, Python (Pandas, NumPy, Matplotlib, Seaborn)  
- Excel, VS Code, Jupyter Notebook, SSMS  
- Data Cleaning, Visualization, Database Design & Management  
- Thrives in stressful environments  
- Goal-oriented, logic-driven problem solver  
- Eager and quick to learn  

## Relevant Experience

`Nov 2022 – Present`  
__Manager – Domino’s Pizza, Rigby, ID__  
- Managed teams of 12 to produce high-quality service in a timely manner  
- Helped raise store quality rating from 2-star to 4-star  
- Performed interviews and ensured strong team staffing  
- Created weekly schedules and managed daily inventory  
- Ensured customer concerns were addressed efficiently  

`Jan 2022 – Oct 2022`  
__Customer Service Operator – AvantGuard, Rexburg, ID__  
- Responded to medical alarm signals quickly and professionally  
- Documented cases accurately for future records  

`Apr 2019 – Aug 2020`  
__Captioning Agent – CaptionCall, ID & NV__  
- Provided real-time captioning services for various conversations  
- Handled unclear audio and technical issues during live calls  

## Education

`Expected 2025`  
__Brigham Young University - Idaho__  
Bachelor of Applied Science and Technology – Database emphasis  

## Other

- Husband and father to one  
- Enjoys cooking, board games, and technology  
- Basic Spanish  

<!-- ### Footer

Last updated: April 2025 -->
